### ISSUE TITLE
Resizable function

### ISSUE THREAD

**Issue by Taxman972** [lf2com/magnet.js#1]
Hi, it's not an issue but a question.
Will you add a resizable function too to this great plugin ?

**Comment by lf2com** [comment]
Hi @Taxman972
Sorry for replying you late.
Did you mean resizing the blocks? Or supporting for resized blocks?

**Comment by Taxman972** [comment]
@lf2com I mean resizing the blocks

**Comment by lf2com** [comment]
@Taxman972 I added this function to both demo pages: [Changes](https://github.com/lf2com/magnet.js/commit/113700c036864460487f151268398493b49fffaa).
I found the following key points:
- The resizing could work only if the block is removed from magnet group because the `mousedown` event would trigger moving block function first, which made resizing not work.
- And the resizing function could be done with CSS style `resize: both` and `overflow: auto`.

Here is the flow about how to resize a block of magnet:
1. Remove the block from magnet group.
2. Resize the block.
3. Add the block back to the magnet group.

For the demo page, you can add/remove the blocks by double clicking or check their checkboxs.

**Comment by Taxman972** [comment]
Thanks, that just what I needed.
