### ISSUE TITLE
Can I directly use magnet.js (master v1.0.1) in my app

### ISSUE THREAD

**Issue by adityakrshnn** [lf2com/magnet.js#11]
I need to make a few tweaks in one of your previous versions (master v1.0.1). It would be really helpful if I could use magnet.js in my app so that I can debug it. Can you provide a way for it?

**Comment by lf2com** [comment]
Hi @adityakrshnn, you can try any of the following ways:
1. If you need the git commits of this repository, do the command `git reset --hard v1.0.1` to rollback the commits.
2. If you don't need the git commits of this repository, just go to the released [v1.0.1](https://github.com/lf2com/magnet.js/releases/tag/v1.0.1) and download the source code then change the codes.

**Comment by adityakrshnn** [comment]
Oh. It seems we are on different pages. I need to use .js file directly instead of min.js in my app. It is because I need to debug the file when its functions are called and trace its flow. How do I do that?

**Comment by lf2com** [comment]
Sorry I misunderstood that! If you had cloned the repository and head on v1.0.1, you could use `npm run build-debug` to build the .min.js without minified. Also I built a v1.0.1 .js file as attach so that you can directly use it.
[magnet-v1.0.1.zip](https://github.com/lf2com/magnet.js/files/3346228/magnet-v1.0.1.zip)

**Comment by adityakrshnn** [comment]
Thanks. This is exactly what I needed.
